### PR TITLE
fix: added italian books translation

### PR DESCRIPTION
**Pull request by grnsmn**
Hi,

I hope this message finds you well. I want continue to contribute to the project and make it more accessible to Italian users.

So, I added the Italian translation of the Bible books to the project and added also some useful abbreviations. Now, Italian users can easily navigate through the Bible books in their native language with your amazing plugin.

I have created a pull request for the changes that I have made. I would greatly appreciate it if you could take a look at it and merge it into the main branch if also here everything looks good to you.

Thank you for your time and for creating such a useful plugin for the Obsidian community. 

God Bless you.
Simone

### CODE REVIEW

**Review by tim-hub — APPROVED** [review]

**Comment by grnsmn** [comment]
Hi @tim-hub 

I hope you're doing well. I noticed that this pull request was approved and the changes were accepted 2 weeks ago. I understand that you might have been busy with other tasks and priorities.

I wanted to check in and inquire about the timeline for merging these changes into the main branch and then integrated in the plugin. The reason I ask is that our Italian community is eager to start using the fantastic `obsidian-bible-reference` plugin, and having these changes integrated would greatly enhance its functionality.

If there are any additional steps or information needed from my end to facilitate the merge process, please let me know, and I'd be happy to assist.

Looking forward to your response and the opportunity to see these improvements become a part of the project.

Thank you!

Best regards 👯 
@grnsmn

**Comment by tim-hub** [comment]
> Hi @tim-hub
> 
> I hope you're doing well. I noticed that this pull request was approved and the changes were accepted 2 weeks ago. I understand that you might have been busy with other tasks and priorities.
> 
> I wanted to check in and inquire about the timeline for merging these changes into the main branch and then integrated in the plugin. The reason I ask is that our Italian community is eager to start using the fantastic `obsidian-bible-reference` plugin, and having these changes integrated would greatly enhance its functionality.
> 
> If there are any additional steps or information needed from my end to facilitate the merge process, please let me know, and I'd be happy to assist.
> 
> Looking forward to your response and the opportunity to see these improvements become a part of the project.
> 
> Thank you!
> 
> Best regards 👯 @grnsmn

Hi @grnsmn

Thanks for the PR and contribution in Obsidian bible reference as well. https://github.com/tim-hub/obsidian-bible-reference

I am actually thinking of re-writing this 

- rewrite this in Typescript. 
- use JSON for different translation
- release a npm package for the work 


Do you mind sharing the Italian translation in a JSON file?

**Comment by tim-hub** [comment]
> Hi @grnsmn
> 
> Hope this message find you well.
> 
> Thanks for your contribution.
> 
> Would you mind make a JSON for Italian translation. Like
> 
> ```
> [
> ...
> ["Nu", "Numeri"]
> ...
> ]
> ```
> 
> > Maybe put it in `lib/translations/it.json`

Or you could just wait for me a bit, 

I will try to make some refactoring by end of this week.

**Comment by grnsmn** [comment]
Hi, @tim-hub  it's a real pleasure to collaborate on this very useful project!

I just added the "translation" folder with the it.json file for the translation of books into Italian inside.

I look forward to your feedback if there is anything still to improve.

**Comment by tim-hub** [comment]
Thanks, I just started the work to make the rewrite. https://github.com/tim-hub/biblejs-name-converter/pull/8

**Review by tim-hub — APPROVED** [review]
book.js change is not needed after the JSON file

**Review by tim-hub — CHANGES_REQUESTED** [review]
do you mind reverting the change in book.js to resolve conflicts? 

Sorry for the inconvenience made here.

**Pull request merged**
